version: 1.3.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  nuget_token:
    secure: BzdLe9enAWcmUiOBMdx02CYt2T+xuLGlvieE2+Ceic8tmFpEb06EOlikWdyOxxbf
  github_token:
    secure: 2LiLyCv5qwnAClSid16P+Yiq+zIyBk+6/Xl1ZDOKz5g6ab2vXosiY3m93n52q1WX
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore .\Leaf.Core.sln
build:
  project: Leaf.Core.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: Leaf.Core\bin\Release\net452
  name: net452
- path: Leaf.Core\bin\Release\net462
  name: net462
- path: Leaf.Core\bin\Release\net472
  name: net472
- path: Leaf.Core\bin\Release\netcoreapp3.0
  name: netcoreapp3.0
deploy:
- provider: NuGet
  api_key:
    secure: BzdLe9enAWcmUiOBMdx02CYt2T+xuLGlvieE2+Ceic8tmFpEb06EOlikWdyOxxbf
  skip_symbols: true
  on:
    branch: master
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Leaf.Core v$(appveyor_build_version)
  auth_token:
    secure: BzdLe9enAWcmUiOBMdx02CYt2T+xuLGlvieE2+Ceic8tmFpEb06EOlikWdyOxxbf
  artifact: net452;net462;net472;netcoreapp3.0
  on:
    branch: master
only_commits:
  files:
    - appveyor.yml
    - Leaf.Core.sln
    - Leaf.Core/Leaf.Core.csproj
    - Leaf.Core/**/*.cs
    - Leaf.Core/**/*.resx
